version: '2'
volumes:
  app_data:
  redis_data:
  
services:
  app:
    image: oficina:aula3-network
    build: .
    volumes:
     - app_data:/tmp
    ports:
     - 80:5000 
  redis:
    image: redis:alpine
    volumes:
     - redis_data:/data

